
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'LcFooter': typeof import("../components/lc/footer/index.vue")['default']
    'LcHeader': typeof import("../components/lc/header/index.vue")['default']
    'LcLogoFooterPets': typeof import("../components/lc/logo/FooterPets.vue")['default']
    'LcLogoLostPets': typeof import("../components/lc/logo/LostPets.vue")['default']
    'LcLogoNoticePets': typeof import("../components/lc/logo/NoticePets.vue")['default']
    'LcLogoPetsCatDog': typeof import("../components/lc/logo/PetsCatDog.vue")['default']
    'LcLogoPetsLogo': typeof import("../components/lc/logo/PetsLogo.vue")['default']
    'LcLogoTargetPets': typeof import("../components/lc/logo/TargetPets.vue")['default']
    'SectionAbout': typeof import("../components/section/About/About.vue")['default']
    'SectionAdminArticleAddarticle': typeof import("../components/section/Admin/article/Addarticle.vue")['default']
    'SectionAdminArticleArticletable': typeof import("../components/section/Admin/article/Articletable.vue")['default']
    'SectionAdminArticleEditarticle': typeof import("../components/section/Admin/article/Editarticle.vue")['default']
    'SectionAdminGalleryAddgallery': typeof import("../components/section/Admin/gallery/Addgallery.vue")['default']
    'SectionAdminGalleryEditgallery': typeof import("../components/section/Admin/gallery/Editgallery.vue")['default']
    'SectionAdminGalleryGallerytable': typeof import("../components/section/Admin/gallery/Gallerytable.vue")['default']
    'SectionAdminPetsAdoptpettable': typeof import("../components/section/Admin/pets/Adoptpettable.vue")['default']
    'SectionAdminPetsEditadoptpet': typeof import("../components/section/Admin/pets/Editadoptpet.vue")['default']
    'SectionAdminPetsEditfindowner': typeof import("../components/section/Admin/pets/Editfindowner.vue")['default']
    'SectionAdminPetsEditlostpets': typeof import("../components/section/Admin/pets/Editlostpets.vue")['default']
    'SectionAdminPetsFindownertable': typeof import("../components/section/Admin/pets/Findownertable.vue")['default']
    'SectionAdminPetsLostpetstable': typeof import("../components/section/Admin/pets/Lostpetstable.vue")['default']
    'SectionAdminPetsNoticeadoptpet': typeof import("../components/section/Admin/pets/Noticeadoptpet.vue")['default']
    'SectionAdminPetsNoticefindowner': typeof import("../components/section/Admin/pets/Noticefindowner.vue")['default']
    'SectionAdminPetsNoticelostpets': typeof import("../components/section/Admin/pets/Noticelostpets.vue")['default']
    'SectionAdminProductAddproduct': typeof import("../components/section/Admin/product/Addproduct.vue")['default']
    'SectionAdminProductEditproduct': typeof import("../components/section/Admin/product/Editproduct.vue")['default']
    'SectionAdminProductProducttable': typeof import("../components/section/Admin/product/Producttable.vue")['default']
    'SectionAdminUserAddUser': typeof import("../components/section/Admin/user/AddUser.vue")['default']
    'SectionAdminUserEditUser': typeof import("../components/section/Admin/user/EditUser.vue")['default']
    'SectionAdminUserUsertable': typeof import("../components/section/Admin/user/Usertable.vue")['default']
    'SectionAllHome': typeof import("../components/section/AllHome.vue")['default']
    'SectionAllHomeuser': typeof import("../components/section/AllHomeuser.vue")['default']
    'SectionArticleArticlepage': typeof import("../components/section/Article/Articlepage.vue")['default']
    'SectionHomeAbouthome': typeof import("../components/section/Home/Abouthome.vue")['default']
    'SectionHomeAboutnotice': typeof import("../components/section/Home/Aboutnotice.vue")['default']
    'SectionHomeAboutnoticeuser': typeof import("../components/section/Home/Aboutnoticeuser.vue")['default']
    'SectionHomeArticlemain': typeof import("../components/section/Home/Articlemain.vue")['default']
    'SectionHomeArticlemainuser': typeof import("../components/section/Home/Articlemainuser.vue")['default']
    'SectionHomeGallery': typeof import("../components/section/Home/Gallery.vue")['default']
    'SectionHomeProductsmain': typeof import("../components/section/Home/Productsmain.vue")['default']
    'SectionHomeProductsmainuser': typeof import("../components/section/Home/Productsmainuser.vue")['default']
    'SectionLogin': typeof import("../components/section/Login.vue")['default']
    'SectionMappin': typeof import("../components/section/Mappin.vue")['default']
    'SectionProductProductspage': typeof import("../components/section/Product/Productspage.vue")['default']
    'SectionProductSortButtons': typeof import("../components/section/Product/SortButtons.vue")['default']
    'SectionRegister': typeof import("../components/section/Register.vue")['default']
    'SectionTestAllpetsold': typeof import("../components/section/Test/Allpetsold.vue")['default']
    'SectionTestTestallpets': typeof import("../components/section/Test/Testallpets.vue")['default']
    'SectionTestTestform1': typeof import("../components/section/Test/Testform1.vue")['default']
    'SectionTestTestnotice': typeof import("../components/section/Test/Testnotice.vue")['default']
    'SectionTestTesttable': typeof import("../components/section/Test/Testtable.vue")['default']
    'SectionUserEdituser': typeof import("../components/section/User/Edituser.vue")['default']
    'SectionUserTabpets': typeof import("../components/section/User/Tabpets.vue")['default']
    'SectionBannerAdoptpetpage': typeof import("../components/section/banner/Adoptpetpage.vue")['default']
    'SectionBannerBannerlostpets': typeof import("../components/section/banner/Bannerlostpets.vue")['default']
    'SectionBannerFindownerpage': typeof import("../components/section/banner/Findownerpage.vue")['default']
    'SectionMiddlewareAdmin': typeof import("../components/section/middleware/admin")['default']
    'SectionMiddlewareAuth': typeof import("../components/section/middleware/auth")['default']
    'SectionPetsAdoptpet': typeof import("../components/section/pets/Adoptpet.vue")['default']
    'SectionPetsAdoptpetuser': typeof import("../components/section/pets/Adoptpetuser.vue")['default']
    'SectionPetsAllpets': typeof import("../components/section/pets/Allpets.vue")['default']
    'SectionPetsAllpetsuser': typeof import("../components/section/pets/Allpetsuser.vue")['default']
    'SectionPetsFindowner': typeof import("../components/section/pets/Findowner.vue")['default']
    'SectionPetsFindowneruser': typeof import("../components/section/pets/Findowneruser.vue")['default']
    'SectionPetsLostpets': typeof import("../components/section/pets/Lostpets.vue")['default']
    'SectionPetsLostpetsuser': typeof import("../components/section/pets/Lostpetsuser.vue")['default']
    'SectionPetsPetButtons': typeof import("../components/section/pets/PetButtons.vue")['default']
    'SectionPetsPetButtonsuser': typeof import("../components/section/pets/PetButtonsuser.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LCircle': typeof import("@vue-leaflet/vue-leaflet")['LCircle']
    'LCircleMarker': typeof import("@vue-leaflet/vue-leaflet")['LCircleMarker']
    'LControl': typeof import("@vue-leaflet/vue-leaflet")['LControl']
    'LControlAttribution': typeof import("@vue-leaflet/vue-leaflet")['LControlAttribution']
    'LControlLayers': typeof import("@vue-leaflet/vue-leaflet")['LControlLayers']
    'LControlScale': typeof import("@vue-leaflet/vue-leaflet")['LControlScale']
    'LControlZoom': typeof import("@vue-leaflet/vue-leaflet")['LControlZoom']
    'LFeatureGroup': typeof import("@vue-leaflet/vue-leaflet")['LFeatureGroup']
    'LGeoJson': typeof import("@vue-leaflet/vue-leaflet")['LGeoJson']
    'LIcon': typeof import("@vue-leaflet/vue-leaflet")['LIcon']
    'LImageOverlay': typeof import("@vue-leaflet/vue-leaflet")['LImageOverlay']
    'LLayerGroup': typeof import("@vue-leaflet/vue-leaflet")['LLayerGroup']
    'LMap': typeof import("@vue-leaflet/vue-leaflet")['LMap']
    'LMarker': typeof import("@vue-leaflet/vue-leaflet")['LMarker']
    'LPolygon': typeof import("@vue-leaflet/vue-leaflet")['LPolygon']
    'LPolyline': typeof import("@vue-leaflet/vue-leaflet")['LPolyline']
    'LPopup': typeof import("@vue-leaflet/vue-leaflet")['LPopup']
    'LRectangle': typeof import("@vue-leaflet/vue-leaflet")['LRectangle']
    'LTileLayer': typeof import("@vue-leaflet/vue-leaflet")['LTileLayer']
    'LTooltip': typeof import("@vue-leaflet/vue-leaflet")['LTooltip']
    'LWmsTileLayer': typeof import("@vue-leaflet/vue-leaflet")['LWmsTileLayer']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyLcFooter': typeof import("../components/lc/footer/index.vue")['default']
    'LazyLcHeader': typeof import("../components/lc/header/index.vue")['default']
    'LazyLcLogoFooterPets': typeof import("../components/lc/logo/FooterPets.vue")['default']
    'LazyLcLogoLostPets': typeof import("../components/lc/logo/LostPets.vue")['default']
    'LazyLcLogoNoticePets': typeof import("../components/lc/logo/NoticePets.vue")['default']
    'LazyLcLogoPetsCatDog': typeof import("../components/lc/logo/PetsCatDog.vue")['default']
    'LazyLcLogoPetsLogo': typeof import("../components/lc/logo/PetsLogo.vue")['default']
    'LazyLcLogoTargetPets': typeof import("../components/lc/logo/TargetPets.vue")['default']
    'LazySectionAbout': typeof import("../components/section/About/About.vue")['default']
    'LazySectionAdminArticleAddarticle': typeof import("../components/section/Admin/article/Addarticle.vue")['default']
    'LazySectionAdminArticleArticletable': typeof import("../components/section/Admin/article/Articletable.vue")['default']
    'LazySectionAdminArticleEditarticle': typeof import("../components/section/Admin/article/Editarticle.vue")['default']
    'LazySectionAdminGalleryAddgallery': typeof import("../components/section/Admin/gallery/Addgallery.vue")['default']
    'LazySectionAdminGalleryEditgallery': typeof import("../components/section/Admin/gallery/Editgallery.vue")['default']
    'LazySectionAdminGalleryGallerytable': typeof import("../components/section/Admin/gallery/Gallerytable.vue")['default']
    'LazySectionAdminPetsAdoptpettable': typeof import("../components/section/Admin/pets/Adoptpettable.vue")['default']
    'LazySectionAdminPetsEditadoptpet': typeof import("../components/section/Admin/pets/Editadoptpet.vue")['default']
    'LazySectionAdminPetsEditfindowner': typeof import("../components/section/Admin/pets/Editfindowner.vue")['default']
    'LazySectionAdminPetsEditlostpets': typeof import("../components/section/Admin/pets/Editlostpets.vue")['default']
    'LazySectionAdminPetsFindownertable': typeof import("../components/section/Admin/pets/Findownertable.vue")['default']
    'LazySectionAdminPetsLostpetstable': typeof import("../components/section/Admin/pets/Lostpetstable.vue")['default']
    'LazySectionAdminPetsNoticeadoptpet': typeof import("../components/section/Admin/pets/Noticeadoptpet.vue")['default']
    'LazySectionAdminPetsNoticefindowner': typeof import("../components/section/Admin/pets/Noticefindowner.vue")['default']
    'LazySectionAdminPetsNoticelostpets': typeof import("../components/section/Admin/pets/Noticelostpets.vue")['default']
    'LazySectionAdminProductAddproduct': typeof import("../components/section/Admin/product/Addproduct.vue")['default']
    'LazySectionAdminProductEditproduct': typeof import("../components/section/Admin/product/Editproduct.vue")['default']
    'LazySectionAdminProductProducttable': typeof import("../components/section/Admin/product/Producttable.vue")['default']
    'LazySectionAdminUserAddUser': typeof import("../components/section/Admin/user/AddUser.vue")['default']
    'LazySectionAdminUserEditUser': typeof import("../components/section/Admin/user/EditUser.vue")['default']
    'LazySectionAdminUserUsertable': typeof import("../components/section/Admin/user/Usertable.vue")['default']
    'LazySectionAllHome': typeof import("../components/section/AllHome.vue")['default']
    'LazySectionAllHomeuser': typeof import("../components/section/AllHomeuser.vue")['default']
    'LazySectionArticleArticlepage': typeof import("../components/section/Article/Articlepage.vue")['default']
    'LazySectionHomeAbouthome': typeof import("../components/section/Home/Abouthome.vue")['default']
    'LazySectionHomeAboutnotice': typeof import("../components/section/Home/Aboutnotice.vue")['default']
    'LazySectionHomeAboutnoticeuser': typeof import("../components/section/Home/Aboutnoticeuser.vue")['default']
    'LazySectionHomeArticlemain': typeof import("../components/section/Home/Articlemain.vue")['default']
    'LazySectionHomeArticlemainuser': typeof import("../components/section/Home/Articlemainuser.vue")['default']
    'LazySectionHomeGallery': typeof import("../components/section/Home/Gallery.vue")['default']
    'LazySectionHomeProductsmain': typeof import("../components/section/Home/Productsmain.vue")['default']
    'LazySectionHomeProductsmainuser': typeof import("../components/section/Home/Productsmainuser.vue")['default']
    'LazySectionLogin': typeof import("../components/section/Login.vue")['default']
    'LazySectionMappin': typeof import("../components/section/Mappin.vue")['default']
    'LazySectionProductProductspage': typeof import("../components/section/Product/Productspage.vue")['default']
    'LazySectionProductSortButtons': typeof import("../components/section/Product/SortButtons.vue")['default']
    'LazySectionRegister': typeof import("../components/section/Register.vue")['default']
    'LazySectionTestAllpetsold': typeof import("../components/section/Test/Allpetsold.vue")['default']
    'LazySectionTestTestallpets': typeof import("../components/section/Test/Testallpets.vue")['default']
    'LazySectionTestTestform1': typeof import("../components/section/Test/Testform1.vue")['default']
    'LazySectionTestTestnotice': typeof import("../components/section/Test/Testnotice.vue")['default']
    'LazySectionTestTesttable': typeof import("../components/section/Test/Testtable.vue")['default']
    'LazySectionUserEdituser': typeof import("../components/section/User/Edituser.vue")['default']
    'LazySectionUserTabpets': typeof import("../components/section/User/Tabpets.vue")['default']
    'LazySectionBannerAdoptpetpage': typeof import("../components/section/banner/Adoptpetpage.vue")['default']
    'LazySectionBannerBannerlostpets': typeof import("../components/section/banner/Bannerlostpets.vue")['default']
    'LazySectionBannerFindownerpage': typeof import("../components/section/banner/Findownerpage.vue")['default']
    'LazySectionMiddlewareAdmin': typeof import("../components/section/middleware/admin")['default']
    'LazySectionMiddlewareAuth': typeof import("../components/section/middleware/auth")['default']
    'LazySectionPetsAdoptpet': typeof import("../components/section/pets/Adoptpet.vue")['default']
    'LazySectionPetsAdoptpetuser': typeof import("../components/section/pets/Adoptpetuser.vue")['default']
    'LazySectionPetsAllpets': typeof import("../components/section/pets/Allpets.vue")['default']
    'LazySectionPetsAllpetsuser': typeof import("../components/section/pets/Allpetsuser.vue")['default']
    'LazySectionPetsFindowner': typeof import("../components/section/pets/Findowner.vue")['default']
    'LazySectionPetsFindowneruser': typeof import("../components/section/pets/Findowneruser.vue")['default']
    'LazySectionPetsLostpets': typeof import("../components/section/pets/Lostpets.vue")['default']
    'LazySectionPetsLostpetsuser': typeof import("../components/section/pets/Lostpetsuser.vue")['default']
    'LazySectionPetsPetButtons': typeof import("../components/section/pets/PetButtons.vue")['default']
    'LazySectionPetsPetButtonsuser': typeof import("../components/section/pets/PetButtonsuser.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyLCircle': typeof import("@vue-leaflet/vue-leaflet")['LCircle']
    'LazyLCircleMarker': typeof import("@vue-leaflet/vue-leaflet")['LCircleMarker']
    'LazyLControl': typeof import("@vue-leaflet/vue-leaflet")['LControl']
    'LazyLControlAttribution': typeof import("@vue-leaflet/vue-leaflet")['LControlAttribution']
    'LazyLControlLayers': typeof import("@vue-leaflet/vue-leaflet")['LControlLayers']
    'LazyLControlScale': typeof import("@vue-leaflet/vue-leaflet")['LControlScale']
    'LazyLControlZoom': typeof import("@vue-leaflet/vue-leaflet")['LControlZoom']
    'LazyLFeatureGroup': typeof import("@vue-leaflet/vue-leaflet")['LFeatureGroup']
    'LazyLGeoJson': typeof import("@vue-leaflet/vue-leaflet")['LGeoJson']
    'LazyLIcon': typeof import("@vue-leaflet/vue-leaflet")['LIcon']
    'LazyLImageOverlay': typeof import("@vue-leaflet/vue-leaflet")['LImageOverlay']
    'LazyLLayerGroup': typeof import("@vue-leaflet/vue-leaflet")['LLayerGroup']
    'LazyLMap': typeof import("@vue-leaflet/vue-leaflet")['LMap']
    'LazyLMarker': typeof import("@vue-leaflet/vue-leaflet")['LMarker']
    'LazyLPolygon': typeof import("@vue-leaflet/vue-leaflet")['LPolygon']
    'LazyLPolyline': typeof import("@vue-leaflet/vue-leaflet")['LPolyline']
    'LazyLPopup': typeof import("@vue-leaflet/vue-leaflet")['LPopup']
    'LazyLRectangle': typeof import("@vue-leaflet/vue-leaflet")['LRectangle']
    'LazyLTileLayer': typeof import("@vue-leaflet/vue-leaflet")['LTileLayer']
    'LazyLTooltip': typeof import("@vue-leaflet/vue-leaflet")['LTooltip']
    'LazyLWmsTileLayer': typeof import("@vue-leaflet/vue-leaflet")['LWmsTileLayer']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const LcFooter: typeof import("../components/lc/footer/index.vue")['default']
export const LcHeader: typeof import("../components/lc/header/index.vue")['default']
export const LcLogoFooterPets: typeof import("../components/lc/logo/FooterPets.vue")['default']
export const LcLogoLostPets: typeof import("../components/lc/logo/LostPets.vue")['default']
export const LcLogoNoticePets: typeof import("../components/lc/logo/NoticePets.vue")['default']
export const LcLogoPetsCatDog: typeof import("../components/lc/logo/PetsCatDog.vue")['default']
export const LcLogoPetsLogo: typeof import("../components/lc/logo/PetsLogo.vue")['default']
export const LcLogoTargetPets: typeof import("../components/lc/logo/TargetPets.vue")['default']
export const SectionAbout: typeof import("../components/section/About/About.vue")['default']
export const SectionAdminArticleAddarticle: typeof import("../components/section/Admin/article/Addarticle.vue")['default']
export const SectionAdminArticleArticletable: typeof import("../components/section/Admin/article/Articletable.vue")['default']
export const SectionAdminArticleEditarticle: typeof import("../components/section/Admin/article/Editarticle.vue")['default']
export const SectionAdminGalleryAddgallery: typeof import("../components/section/Admin/gallery/Addgallery.vue")['default']
export const SectionAdminGalleryEditgallery: typeof import("../components/section/Admin/gallery/Editgallery.vue")['default']
export const SectionAdminGalleryGallerytable: typeof import("../components/section/Admin/gallery/Gallerytable.vue")['default']
export const SectionAdminPetsAdoptpettable: typeof import("../components/section/Admin/pets/Adoptpettable.vue")['default']
export const SectionAdminPetsEditadoptpet: typeof import("../components/section/Admin/pets/Editadoptpet.vue")['default']
export const SectionAdminPetsEditfindowner: typeof import("../components/section/Admin/pets/Editfindowner.vue")['default']
export const SectionAdminPetsEditlostpets: typeof import("../components/section/Admin/pets/Editlostpets.vue")['default']
export const SectionAdminPetsFindownertable: typeof import("../components/section/Admin/pets/Findownertable.vue")['default']
export const SectionAdminPetsLostpetstable: typeof import("../components/section/Admin/pets/Lostpetstable.vue")['default']
export const SectionAdminPetsNoticeadoptpet: typeof import("../components/section/Admin/pets/Noticeadoptpet.vue")['default']
export const SectionAdminPetsNoticefindowner: typeof import("../components/section/Admin/pets/Noticefindowner.vue")['default']
export const SectionAdminPetsNoticelostpets: typeof import("../components/section/Admin/pets/Noticelostpets.vue")['default']
export const SectionAdminProductAddproduct: typeof import("../components/section/Admin/product/Addproduct.vue")['default']
export const SectionAdminProductEditproduct: typeof import("../components/section/Admin/product/Editproduct.vue")['default']
export const SectionAdminProductProducttable: typeof import("../components/section/Admin/product/Producttable.vue")['default']
export const SectionAdminUserAddUser: typeof import("../components/section/Admin/user/AddUser.vue")['default']
export const SectionAdminUserEditUser: typeof import("../components/section/Admin/user/EditUser.vue")['default']
export const SectionAdminUserUsertable: typeof import("../components/section/Admin/user/Usertable.vue")['default']
export const SectionAllHome: typeof import("../components/section/AllHome.vue")['default']
export const SectionAllHomeuser: typeof import("../components/section/AllHomeuser.vue")['default']
export const SectionArticleArticlepage: typeof import("../components/section/Article/Articlepage.vue")['default']
export const SectionHomeAbouthome: typeof import("../components/section/Home/Abouthome.vue")['default']
export const SectionHomeAboutnotice: typeof import("../components/section/Home/Aboutnotice.vue")['default']
export const SectionHomeAboutnoticeuser: typeof import("../components/section/Home/Aboutnoticeuser.vue")['default']
export const SectionHomeArticlemain: typeof import("../components/section/Home/Articlemain.vue")['default']
export const SectionHomeArticlemainuser: typeof import("../components/section/Home/Articlemainuser.vue")['default']
export const SectionHomeGallery: typeof import("../components/section/Home/Gallery.vue")['default']
export const SectionHomeProductsmain: typeof import("../components/section/Home/Productsmain.vue")['default']
export const SectionHomeProductsmainuser: typeof import("../components/section/Home/Productsmainuser.vue")['default']
export const SectionLogin: typeof import("../components/section/Login.vue")['default']
export const SectionMappin: typeof import("../components/section/Mappin.vue")['default']
export const SectionProductProductspage: typeof import("../components/section/Product/Productspage.vue")['default']
export const SectionProductSortButtons: typeof import("../components/section/Product/SortButtons.vue")['default']
export const SectionRegister: typeof import("../components/section/Register.vue")['default']
export const SectionTestAllpetsold: typeof import("../components/section/Test/Allpetsold.vue")['default']
export const SectionTestTestallpets: typeof import("../components/section/Test/Testallpets.vue")['default']
export const SectionTestTestform1: typeof import("../components/section/Test/Testform1.vue")['default']
export const SectionTestTestnotice: typeof import("../components/section/Test/Testnotice.vue")['default']
export const SectionTestTesttable: typeof import("../components/section/Test/Testtable.vue")['default']
export const SectionUserEdituser: typeof import("../components/section/User/Edituser.vue")['default']
export const SectionUserTabpets: typeof import("../components/section/User/Tabpets.vue")['default']
export const SectionBannerAdoptpetpage: typeof import("../components/section/banner/Adoptpetpage.vue")['default']
export const SectionBannerBannerlostpets: typeof import("../components/section/banner/Bannerlostpets.vue")['default']
export const SectionBannerFindownerpage: typeof import("../components/section/banner/Findownerpage.vue")['default']
export const SectionMiddlewareAdmin: typeof import("../components/section/middleware/admin")['default']
export const SectionMiddlewareAuth: typeof import("../components/section/middleware/auth")['default']
export const SectionPetsAdoptpet: typeof import("../components/section/pets/Adoptpet.vue")['default']
export const SectionPetsAdoptpetuser: typeof import("../components/section/pets/Adoptpetuser.vue")['default']
export const SectionPetsAllpets: typeof import("../components/section/pets/Allpets.vue")['default']
export const SectionPetsAllpetsuser: typeof import("../components/section/pets/Allpetsuser.vue")['default']
export const SectionPetsFindowner: typeof import("../components/section/pets/Findowner.vue")['default']
export const SectionPetsFindowneruser: typeof import("../components/section/pets/Findowneruser.vue")['default']
export const SectionPetsLostpets: typeof import("../components/section/pets/Lostpets.vue")['default']
export const SectionPetsLostpetsuser: typeof import("../components/section/pets/Lostpetsuser.vue")['default']
export const SectionPetsPetButtons: typeof import("../components/section/pets/PetButtons.vue")['default']
export const SectionPetsPetButtonsuser: typeof import("../components/section/pets/PetButtonsuser.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LCircle: typeof import("@vue-leaflet/vue-leaflet")['LCircle']
export const LCircleMarker: typeof import("@vue-leaflet/vue-leaflet")['LCircleMarker']
export const LControl: typeof import("@vue-leaflet/vue-leaflet")['LControl']
export const LControlAttribution: typeof import("@vue-leaflet/vue-leaflet")['LControlAttribution']
export const LControlLayers: typeof import("@vue-leaflet/vue-leaflet")['LControlLayers']
export const LControlScale: typeof import("@vue-leaflet/vue-leaflet")['LControlScale']
export const LControlZoom: typeof import("@vue-leaflet/vue-leaflet")['LControlZoom']
export const LFeatureGroup: typeof import("@vue-leaflet/vue-leaflet")['LFeatureGroup']
export const LGeoJson: typeof import("@vue-leaflet/vue-leaflet")['LGeoJson']
export const LIcon: typeof import("@vue-leaflet/vue-leaflet")['LIcon']
export const LImageOverlay: typeof import("@vue-leaflet/vue-leaflet")['LImageOverlay']
export const LLayerGroup: typeof import("@vue-leaflet/vue-leaflet")['LLayerGroup']
export const LMap: typeof import("@vue-leaflet/vue-leaflet")['LMap']
export const LMarker: typeof import("@vue-leaflet/vue-leaflet")['LMarker']
export const LPolygon: typeof import("@vue-leaflet/vue-leaflet")['LPolygon']
export const LPolyline: typeof import("@vue-leaflet/vue-leaflet")['LPolyline']
export const LPopup: typeof import("@vue-leaflet/vue-leaflet")['LPopup']
export const LRectangle: typeof import("@vue-leaflet/vue-leaflet")['LRectangle']
export const LTileLayer: typeof import("@vue-leaflet/vue-leaflet")['LTileLayer']
export const LTooltip: typeof import("@vue-leaflet/vue-leaflet")['LTooltip']
export const LWmsTileLayer: typeof import("@vue-leaflet/vue-leaflet")['LWmsTileLayer']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyLcFooter: typeof import("../components/lc/footer/index.vue")['default']
export const LazyLcHeader: typeof import("../components/lc/header/index.vue")['default']
export const LazyLcLogoFooterPets: typeof import("../components/lc/logo/FooterPets.vue")['default']
export const LazyLcLogoLostPets: typeof import("../components/lc/logo/LostPets.vue")['default']
export const LazyLcLogoNoticePets: typeof import("../components/lc/logo/NoticePets.vue")['default']
export const LazyLcLogoPetsCatDog: typeof import("../components/lc/logo/PetsCatDog.vue")['default']
export const LazyLcLogoPetsLogo: typeof import("../components/lc/logo/PetsLogo.vue")['default']
export const LazyLcLogoTargetPets: typeof import("../components/lc/logo/TargetPets.vue")['default']
export const LazySectionAbout: typeof import("../components/section/About/About.vue")['default']
export const LazySectionAdminArticleAddarticle: typeof import("../components/section/Admin/article/Addarticle.vue")['default']
export const LazySectionAdminArticleArticletable: typeof import("../components/section/Admin/article/Articletable.vue")['default']
export const LazySectionAdminArticleEditarticle: typeof import("../components/section/Admin/article/Editarticle.vue")['default']
export const LazySectionAdminGalleryAddgallery: typeof import("../components/section/Admin/gallery/Addgallery.vue")['default']
export const LazySectionAdminGalleryEditgallery: typeof import("../components/section/Admin/gallery/Editgallery.vue")['default']
export const LazySectionAdminGalleryGallerytable: typeof import("../components/section/Admin/gallery/Gallerytable.vue")['default']
export const LazySectionAdminPetsAdoptpettable: typeof import("../components/section/Admin/pets/Adoptpettable.vue")['default']
export const LazySectionAdminPetsEditadoptpet: typeof import("../components/section/Admin/pets/Editadoptpet.vue")['default']
export const LazySectionAdminPetsEditfindowner: typeof import("../components/section/Admin/pets/Editfindowner.vue")['default']
export const LazySectionAdminPetsEditlostpets: typeof import("../components/section/Admin/pets/Editlostpets.vue")['default']
export const LazySectionAdminPetsFindownertable: typeof import("../components/section/Admin/pets/Findownertable.vue")['default']
export const LazySectionAdminPetsLostpetstable: typeof import("../components/section/Admin/pets/Lostpetstable.vue")['default']
export const LazySectionAdminPetsNoticeadoptpet: typeof import("../components/section/Admin/pets/Noticeadoptpet.vue")['default']
export const LazySectionAdminPetsNoticefindowner: typeof import("../components/section/Admin/pets/Noticefindowner.vue")['default']
export const LazySectionAdminPetsNoticelostpets: typeof import("../components/section/Admin/pets/Noticelostpets.vue")['default']
export const LazySectionAdminProductAddproduct: typeof import("../components/section/Admin/product/Addproduct.vue")['default']
export const LazySectionAdminProductEditproduct: typeof import("../components/section/Admin/product/Editproduct.vue")['default']
export const LazySectionAdminProductProducttable: typeof import("../components/section/Admin/product/Producttable.vue")['default']
export const LazySectionAdminUserAddUser: typeof import("../components/section/Admin/user/AddUser.vue")['default']
export const LazySectionAdminUserEditUser: typeof import("../components/section/Admin/user/EditUser.vue")['default']
export const LazySectionAdminUserUsertable: typeof import("../components/section/Admin/user/Usertable.vue")['default']
export const LazySectionAllHome: typeof import("../components/section/AllHome.vue")['default']
export const LazySectionAllHomeuser: typeof import("../components/section/AllHomeuser.vue")['default']
export const LazySectionArticleArticlepage: typeof import("../components/section/Article/Articlepage.vue")['default']
export const LazySectionHomeAbouthome: typeof import("../components/section/Home/Abouthome.vue")['default']
export const LazySectionHomeAboutnotice: typeof import("../components/section/Home/Aboutnotice.vue")['default']
export const LazySectionHomeAboutnoticeuser: typeof import("../components/section/Home/Aboutnoticeuser.vue")['default']
export const LazySectionHomeArticlemain: typeof import("../components/section/Home/Articlemain.vue")['default']
export const LazySectionHomeArticlemainuser: typeof import("../components/section/Home/Articlemainuser.vue")['default']
export const LazySectionHomeGallery: typeof import("../components/section/Home/Gallery.vue")['default']
export const LazySectionHomeProductsmain: typeof import("../components/section/Home/Productsmain.vue")['default']
export const LazySectionHomeProductsmainuser: typeof import("../components/section/Home/Productsmainuser.vue")['default']
export const LazySectionLogin: typeof import("../components/section/Login.vue")['default']
export const LazySectionMappin: typeof import("../components/section/Mappin.vue")['default']
export const LazySectionProductProductspage: typeof import("../components/section/Product/Productspage.vue")['default']
export const LazySectionProductSortButtons: typeof import("../components/section/Product/SortButtons.vue")['default']
export const LazySectionRegister: typeof import("../components/section/Register.vue")['default']
export const LazySectionTestAllpetsold: typeof import("../components/section/Test/Allpetsold.vue")['default']
export const LazySectionTestTestallpets: typeof import("../components/section/Test/Testallpets.vue")['default']
export const LazySectionTestTestform1: typeof import("../components/section/Test/Testform1.vue")['default']
export const LazySectionTestTestnotice: typeof import("../components/section/Test/Testnotice.vue")['default']
export const LazySectionTestTesttable: typeof import("../components/section/Test/Testtable.vue")['default']
export const LazySectionUserEdituser: typeof import("../components/section/User/Edituser.vue")['default']
export const LazySectionUserTabpets: typeof import("../components/section/User/Tabpets.vue")['default']
export const LazySectionBannerAdoptpetpage: typeof import("../components/section/banner/Adoptpetpage.vue")['default']
export const LazySectionBannerBannerlostpets: typeof import("../components/section/banner/Bannerlostpets.vue")['default']
export const LazySectionBannerFindownerpage: typeof import("../components/section/banner/Findownerpage.vue")['default']
export const LazySectionMiddlewareAdmin: typeof import("../components/section/middleware/admin")['default']
export const LazySectionMiddlewareAuth: typeof import("../components/section/middleware/auth")['default']
export const LazySectionPetsAdoptpet: typeof import("../components/section/pets/Adoptpet.vue")['default']
export const LazySectionPetsAdoptpetuser: typeof import("../components/section/pets/Adoptpetuser.vue")['default']
export const LazySectionPetsAllpets: typeof import("../components/section/pets/Allpets.vue")['default']
export const LazySectionPetsAllpetsuser: typeof import("../components/section/pets/Allpetsuser.vue")['default']
export const LazySectionPetsFindowner: typeof import("../components/section/pets/Findowner.vue")['default']
export const LazySectionPetsFindowneruser: typeof import("../components/section/pets/Findowneruser.vue")['default']
export const LazySectionPetsLostpets: typeof import("../components/section/pets/Lostpets.vue")['default']
export const LazySectionPetsLostpetsuser: typeof import("../components/section/pets/Lostpetsuser.vue")['default']
export const LazySectionPetsPetButtons: typeof import("../components/section/pets/PetButtons.vue")['default']
export const LazySectionPetsPetButtonsuser: typeof import("../components/section/pets/PetButtonsuser.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyLCircle: typeof import("@vue-leaflet/vue-leaflet")['LCircle']
export const LazyLCircleMarker: typeof import("@vue-leaflet/vue-leaflet")['LCircleMarker']
export const LazyLControl: typeof import("@vue-leaflet/vue-leaflet")['LControl']
export const LazyLControlAttribution: typeof import("@vue-leaflet/vue-leaflet")['LControlAttribution']
export const LazyLControlLayers: typeof import("@vue-leaflet/vue-leaflet")['LControlLayers']
export const LazyLControlScale: typeof import("@vue-leaflet/vue-leaflet")['LControlScale']
export const LazyLControlZoom: typeof import("@vue-leaflet/vue-leaflet")['LControlZoom']
export const LazyLFeatureGroup: typeof import("@vue-leaflet/vue-leaflet")['LFeatureGroup']
export const LazyLGeoJson: typeof import("@vue-leaflet/vue-leaflet")['LGeoJson']
export const LazyLIcon: typeof import("@vue-leaflet/vue-leaflet")['LIcon']
export const LazyLImageOverlay: typeof import("@vue-leaflet/vue-leaflet")['LImageOverlay']
export const LazyLLayerGroup: typeof import("@vue-leaflet/vue-leaflet")['LLayerGroup']
export const LazyLMap: typeof import("@vue-leaflet/vue-leaflet")['LMap']
export const LazyLMarker: typeof import("@vue-leaflet/vue-leaflet")['LMarker']
export const LazyLPolygon: typeof import("@vue-leaflet/vue-leaflet")['LPolygon']
export const LazyLPolyline: typeof import("@vue-leaflet/vue-leaflet")['LPolyline']
export const LazyLPopup: typeof import("@vue-leaflet/vue-leaflet")['LPopup']
export const LazyLRectangle: typeof import("@vue-leaflet/vue-leaflet")['LRectangle']
export const LazyLTileLayer: typeof import("@vue-leaflet/vue-leaflet")['LTileLayer']
export const LazyLTooltip: typeof import("@vue-leaflet/vue-leaflet")['LTooltip']
export const LazyLWmsTileLayer: typeof import("@vue-leaflet/vue-leaflet")['LWmsTileLayer']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
