
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'LcAdmin': typeof import("../components/lc/admin/index.vue")['default']
    'LcFooter': typeof import("../components/lc/footer/index.vue")['default']
    'LcHeader': typeof import("../components/lc/header/index.vue")['default']
    'LcLogoFooterPets': typeof import("../components/lc/logo/FooterPets.vue")['default']
    'LcLogoLostPets': typeof import("../components/lc/logo/LostPets.vue")['default']
    'LcLogoNoticePets': typeof import("../components/lc/logo/NoticePets.vue")['default']
    'LcLogoPetsCatDog': typeof import("../components/lc/logo/PetsCatDog.vue")['default']
    'LcLogoPetsLogo': typeof import("../components/lc/logo/PetsLogo.vue")['default']
    'LcLogoTargetPets': typeof import("../components/lc/logo/TargetPets.vue")['default']
    'LcUser': typeof import("../components/lc/user/index.vue")['default']
    'SectionAbout': typeof import("../components/section/About/About.vue")['default']
    'SectionAdminAdoptpettable': typeof import("../components/section/Admin/Adoptpettable.vue")['default']
    'SectionAdminFindownertable': typeof import("../components/section/Admin/Findownertable.vue")['default']
    'SectionAdminGallerytable': typeof import("../components/section/Admin/Gallerytable.vue")['default']
    'SectionAdminLostpetstable': typeof import("../components/section/Admin/Lostpetstable.vue")['default']
    'SectionAdminProducttable': typeof import("../components/section/Admin/Producttable.vue")['default']
    'SectionAdminUsertable': typeof import("../components/section/Admin/Usertable.vue")['default']
    'SectionAdoptpetAdoptpetpage': typeof import("../components/section/Adoptpet/Adoptpetpage.vue")['default']
    'SectionAllAdmin': typeof import("../components/section/AllAdmin.vue")['default']
    'SectionAllAdoptpet': typeof import("../components/section/AllAdoptpet.vue")['default']
    'SectionAllArticle': typeof import("../components/section/AllArticle.vue")['default']
    'SectionAllBanner': typeof import("../components/section/AllBanner.vue")['default']
    'SectionAllFindowner': typeof import("../components/section/AllFindowner.vue")['default']
    'SectionAllHome': typeof import("../components/section/AllHome.vue")['default']
    'SectionAllProducts': typeof import("../components/section/AllProducts.vue")['default']
    'SectionArticleArticlemain': typeof import("../components/section/Article/Articlemain.vue")['default']
    'SectionArticleArticlepage': typeof import("../components/section/Article/Articlepage.vue")['default']
    'SectionEditusee': typeof import("../components/section/Edituser.vue")['default']
    'SectionFindownerFindownerpage': typeof import("../components/section/Findowner/Findownerpage.vue")['default']
    'SectionHomeAbouthome': typeof import("../components/section/Home/Abouthome.vue")['default']
    'SectionHomeAboutnoticehome': typeof import("../components/section/Home/Aboutnoticehome.vue")['default']
    'SectionLogin': typeof import("../components/section/Login.vue")['default']
    'SectionMappin': typeof import("../components/section/Mappin.vue")['default']
    'SectionProductProductsmain': typeof import("../components/section/Product/Productsmain.vue")['default']
    'SectionProductProductspage': typeof import("../components/section/Product/Productspage.vue")['default']
    'SectionProductSortButtons': typeof import("../components/section/Product/SortButtons.vue")['default']
    'SectionRegister': typeof import("../components/section/Register.vue")['default']
    'SectionTest': typeof import("../components/section/Test.vue")['default']
    'SectionUserTabpets': typeof import("../components/section/User/Tabpets.vue")['default']
    'SectionBannerBannerlostpets': typeof import("../components/section/banner/Bannerlostpets.vue")['default']
    'SectionBannerGallery': typeof import("../components/section/banner/Gallery.vue")['default']
    'SectionPetsAdoptpet': typeof import("../components/section/pets/Adoptpet.vue")['default']
    'SectionPetsAllpets': typeof import("../components/section/pets/Allpets.vue")['default']
    'SectionPetsFindowner': typeof import("../components/section/pets/Findowner.vue")['default']
    'SectionPetsImageUpload': typeof import("../components/section/pets/ImageUpload.vue")['default']
    'SectionPetsLostpets': typeof import("../components/section/pets/Lostpets.vue")['default']
    'SectionPetsNoticeadoptpet': typeof import("../components/section/pets/Noticeadoptpet.vue")['default']
    'SectionPetsNoticefindowner': typeof import("../components/section/pets/Noticefindowner.vue")['default']
    'SectionPetsNoticelostpets': typeof import("../components/section/pets/Noticelostpets.vue")['default']
    'SectionPetsPetButtons': typeof import("../components/section/pets/PetButtons.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LCircle': typeof import("@vue-leaflet/vue-leaflet")['LCircle']
    'LCircleMarker': typeof import("@vue-leaflet/vue-leaflet")['LCircleMarker']
    'LControl': typeof import("@vue-leaflet/vue-leaflet")['LControl']
    'LControlAttribution': typeof import("@vue-leaflet/vue-leaflet")['LControlAttribution']
    'LControlLayers': typeof import("@vue-leaflet/vue-leaflet")['LControlLayers']
    'LControlScale': typeof import("@vue-leaflet/vue-leaflet")['LControlScale']
    'LControlZoom': typeof import("@vue-leaflet/vue-leaflet")['LControlZoom']
    'LFeatureGroup': typeof import("@vue-leaflet/vue-leaflet")['LFeatureGroup']
    'LGeoJson': typeof import("@vue-leaflet/vue-leaflet")['LGeoJson']
    'LIcon': typeof import("@vue-leaflet/vue-leaflet")['LIcon']
    'LImageOverlay': typeof import("@vue-leaflet/vue-leaflet")['LImageOverlay']
    'LLayerGroup': typeof import("@vue-leaflet/vue-leaflet")['LLayerGroup']
    'LMap': typeof import("@vue-leaflet/vue-leaflet")['LMap']
    'LMarker': typeof import("@vue-leaflet/vue-leaflet")['LMarker']
    'LPolygon': typeof import("@vue-leaflet/vue-leaflet")['LPolygon']
    'LPolyline': typeof import("@vue-leaflet/vue-leaflet")['LPolyline']
    'LPopup': typeof import("@vue-leaflet/vue-leaflet")['LPopup']
    'LRectangle': typeof import("@vue-leaflet/vue-leaflet")['LRectangle']
    'LTileLayer': typeof import("@vue-leaflet/vue-leaflet")['LTileLayer']
    'LTooltip': typeof import("@vue-leaflet/vue-leaflet")['LTooltip']
    'LWmsTileLayer': typeof import("@vue-leaflet/vue-leaflet")['LWmsTileLayer']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyLcAdmin': typeof import("../components/lc/admin/index.vue")['default']
    'LazyLcFooter': typeof import("../components/lc/footer/index.vue")['default']
    'LazyLcHeader': typeof import("../components/lc/header/index.vue")['default']
    'LazyLcLogoFooterPets': typeof import("../components/lc/logo/FooterPets.vue")['default']
    'LazyLcLogoLostPets': typeof import("../components/lc/logo/LostPets.vue")['default']
    'LazyLcLogoNoticePets': typeof import("../components/lc/logo/NoticePets.vue")['default']
    'LazyLcLogoPetsCatDog': typeof import("../components/lc/logo/PetsCatDog.vue")['default']
    'LazyLcLogoPetsLogo': typeof import("../components/lc/logo/PetsLogo.vue")['default']
    'LazyLcLogoTargetPets': typeof import("../components/lc/logo/TargetPets.vue")['default']
    'LazyLcUser': typeof import("../components/lc/user/index.vue")['default']
    'LazySectionAbout': typeof import("../components/section/About/About.vue")['default']
    'LazySectionAdminAdoptpettable': typeof import("../components/section/Admin/Adoptpettable.vue")['default']
    'LazySectionAdminFindownertable': typeof import("../components/section/Admin/Findownertable.vue")['default']
    'LazySectionAdminGallerytable': typeof import("../components/section/Admin/Gallerytable.vue")['default']
    'LazySectionAdminLostpetstable': typeof import("../components/section/Admin/Lostpetstable.vue")['default']
    'LazySectionAdminProducttable': typeof import("../components/section/Admin/Producttable.vue")['default']
    'LazySectionAdminUsertable': typeof import("../components/section/Admin/Usertable.vue")['default']
    'LazySectionAdoptpetAdoptpetpage': typeof import("../components/section/Adoptpet/Adoptpetpage.vue")['default']
    'LazySectionAllAdmin': typeof import("../components/section/AllAdmin.vue")['default']
    'LazySectionAllAdoptpet': typeof import("../components/section/AllAdoptpet.vue")['default']
    'LazySectionAllArticle': typeof import("../components/section/AllArticle.vue")['default']
    'LazySectionAllBanner': typeof import("../components/section/AllBanner.vue")['default']
    'LazySectionAllFindowner': typeof import("../components/section/AllFindowner.vue")['default']
    'LazySectionAllHome': typeof import("../components/section/AllHome.vue")['default']
    'LazySectionAllProducts': typeof import("../components/section/AllProducts.vue")['default']
    'LazySectionArticleArticlemain': typeof import("../components/section/Article/Articlemain.vue")['default']
    'LazySectionArticleArticlepage': typeof import("../components/section/Article/Articlepage.vue")['default']
    'LazySectionEditusee': typeof import("../components/section/Edituser.vue")['default']
    'LazySectionFindownerFindownerpage': typeof import("../components/section/Findowner/Findownerpage.vue")['default']
    'LazySectionHomeAbouthome': typeof import("../components/section/Home/Abouthome.vue")['default']
    'LazySectionHomeAboutnoticehome': typeof import("../components/section/Home/Aboutnoticehome.vue")['default']
    'LazySectionLogin': typeof import("../components/section/Login.vue")['default']
    'LazySectionMappin': typeof import("../components/section/Mappin.vue")['default']
    'LazySectionProductProductsmain': typeof import("../components/section/Product/Productsmain.vue")['default']
    'LazySectionProductProductspage': typeof import("../components/section/Product/Productspage.vue")['default']
    'LazySectionProductSortButtons': typeof import("../components/section/Product/SortButtons.vue")['default']
    'LazySectionRegister': typeof import("../components/section/Register.vue")['default']
    'LazySectionTest': typeof import("../components/section/Test.vue")['default']
    'LazySectionUserTabpets': typeof import("../components/section/User/Tabpets.vue")['default']
    'LazySectionBannerBannerlostpets': typeof import("../components/section/banner/Bannerlostpets.vue")['default']
    'LazySectionBannerGallery': typeof import("../components/section/banner/Gallery.vue")['default']
    'LazySectionPetsAdoptpet': typeof import("../components/section/pets/Adoptpet.vue")['default']
    'LazySectionPetsAllpets': typeof import("../components/section/pets/Allpets.vue")['default']
    'LazySectionPetsFindowner': typeof import("../components/section/pets/Findowner.vue")['default']
    'LazySectionPetsImageUpload': typeof import("../components/section/pets/ImageUpload.vue")['default']
    'LazySectionPetsLostpets': typeof import("../components/section/pets/Lostpets.vue")['default']
    'LazySectionPetsNoticeadoptpet': typeof import("../components/section/pets/Noticeadoptpet.vue")['default']
    'LazySectionPetsNoticefindowner': typeof import("../components/section/pets/Noticefindowner.vue")['default']
    'LazySectionPetsNoticelostpets': typeof import("../components/section/pets/Noticelostpets.vue")['default']
    'LazySectionPetsPetButtons': typeof import("../components/section/pets/PetButtons.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyLCircle': typeof import("@vue-leaflet/vue-leaflet")['LCircle']
    'LazyLCircleMarker': typeof import("@vue-leaflet/vue-leaflet")['LCircleMarker']
    'LazyLControl': typeof import("@vue-leaflet/vue-leaflet")['LControl']
    'LazyLControlAttribution': typeof import("@vue-leaflet/vue-leaflet")['LControlAttribution']
    'LazyLControlLayers': typeof import("@vue-leaflet/vue-leaflet")['LControlLayers']
    'LazyLControlScale': typeof import("@vue-leaflet/vue-leaflet")['LControlScale']
    'LazyLControlZoom': typeof import("@vue-leaflet/vue-leaflet")['LControlZoom']
    'LazyLFeatureGroup': typeof import("@vue-leaflet/vue-leaflet")['LFeatureGroup']
    'LazyLGeoJson': typeof import("@vue-leaflet/vue-leaflet")['LGeoJson']
    'LazyLIcon': typeof import("@vue-leaflet/vue-leaflet")['LIcon']
    'LazyLImageOverlay': typeof import("@vue-leaflet/vue-leaflet")['LImageOverlay']
    'LazyLLayerGroup': typeof import("@vue-leaflet/vue-leaflet")['LLayerGroup']
    'LazyLMap': typeof import("@vue-leaflet/vue-leaflet")['LMap']
    'LazyLMarker': typeof import("@vue-leaflet/vue-leaflet")['LMarker']
    'LazyLPolygon': typeof import("@vue-leaflet/vue-leaflet")['LPolygon']
    'LazyLPolyline': typeof import("@vue-leaflet/vue-leaflet")['LPolyline']
    'LazyLPopup': typeof import("@vue-leaflet/vue-leaflet")['LPopup']
    'LazyLRectangle': typeof import("@vue-leaflet/vue-leaflet")['LRectangle']
    'LazyLTileLayer': typeof import("@vue-leaflet/vue-leaflet")['LTileLayer']
    'LazyLTooltip': typeof import("@vue-leaflet/vue-leaflet")['LTooltip']
    'LazyLWmsTileLayer': typeof import("@vue-leaflet/vue-leaflet")['LWmsTileLayer']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const LcAdmin: typeof import("../components/lc/admin/index.vue")['default']
export const LcFooter: typeof import("../components/lc/footer/index.vue")['default']
export const LcHeader: typeof import("../components/lc/header/index.vue")['default']
export const LcLogoFooterPets: typeof import("../components/lc/logo/FooterPets.vue")['default']
export const LcLogoLostPets: typeof import("../components/lc/logo/LostPets.vue")['default']
export const LcLogoNoticePets: typeof import("../components/lc/logo/NoticePets.vue")['default']
export const LcLogoPetsCatDog: typeof import("../components/lc/logo/PetsCatDog.vue")['default']
export const LcLogoPetsLogo: typeof import("../components/lc/logo/PetsLogo.vue")['default']
export const LcLogoTargetPets: typeof import("../components/lc/logo/TargetPets.vue")['default']
export const LcUser: typeof import("../components/lc/user/index.vue")['default']
export const SectionAbout: typeof import("../components/section/About/About.vue")['default']
export const SectionAdminAdoptpettable: typeof import("../components/section/Admin/Adoptpettable.vue")['default']
export const SectionAdminFindownertable: typeof import("../components/section/Admin/Findownertable.vue")['default']
export const SectionAdminGallerytable: typeof import("../components/section/Admin/Gallerytable.vue")['default']
export const SectionAdminLostpetstable: typeof import("../components/section/Admin/Lostpetstable.vue")['default']
export const SectionAdminProducttable: typeof import("../components/section/Admin/Producttable.vue")['default']
export const SectionAdminUsertable: typeof import("../components/section/Admin/Usertable.vue")['default']
export const SectionAdoptpetAdoptpetpage: typeof import("../components/section/Adoptpet/Adoptpetpage.vue")['default']
export const SectionAllAdmin: typeof import("../components/section/AllAdmin.vue")['default']
export const SectionAllAdoptpet: typeof import("../components/section/AllAdoptpet.vue")['default']
export const SectionAllArticle: typeof import("../components/section/AllArticle.vue")['default']
export const SectionAllBanner: typeof import("../components/section/AllBanner.vue")['default']
export const SectionAllFindowner: typeof import("../components/section/AllFindowner.vue")['default']
export const SectionAllHome: typeof import("../components/section/AllHome.vue")['default']
export const SectionAllProducts: typeof import("../components/section/AllProducts.vue")['default']
export const SectionArticleArticlemain: typeof import("../components/section/Article/Articlemain.vue")['default']
export const SectionArticleArticlepage: typeof import("../components/section/Article/Articlepage.vue")['default']
export const SectionEditusee: typeof import("../components/section/Edituser.vue")['default']
export const SectionFindownerFindownerpage: typeof import("../components/section/Findowner/Findownerpage.vue")['default']
export const SectionHomeAbouthome: typeof import("../components/section/Home/Abouthome.vue")['default']
export const SectionHomeAboutnoticehome: typeof import("../components/section/Home/Aboutnoticehome.vue")['default']
export const SectionLogin: typeof import("../components/section/Login.vue")['default']
export const SectionMappin: typeof import("../components/section/Mappin.vue")['default']
export const SectionProductProductsmain: typeof import("../components/section/Product/Productsmain.vue")['default']
export const SectionProductProductspage: typeof import("../components/section/Product/Productspage.vue")['default']
export const SectionProductSortButtons: typeof import("../components/section/Product/SortButtons.vue")['default']
export const SectionRegister: typeof import("../components/section/Register.vue")['default']
export const SectionTest: typeof import("../components/section/Test.vue")['default']
export const SectionUserTabpets: typeof import("../components/section/User/Tabpets.vue")['default']
export const SectionBannerBannerlostpets: typeof import("../components/section/banner/Bannerlostpets.vue")['default']
export const SectionBannerGallery: typeof import("../components/section/banner/Gallery.vue")['default']
export const SectionPetsAdoptpet: typeof import("../components/section/pets/Adoptpet.vue")['default']
export const SectionPetsAllpets: typeof import("../components/section/pets/Allpets.vue")['default']
export const SectionPetsFindowner: typeof import("../components/section/pets/Findowner.vue")['default']
export const SectionPetsImageUpload: typeof import("../components/section/pets/ImageUpload.vue")['default']
export const SectionPetsLostpets: typeof import("../components/section/pets/Lostpets.vue")['default']
export const SectionPetsNoticeadoptpet: typeof import("../components/section/pets/Noticeadoptpet.vue")['default']
export const SectionPetsNoticefindowner: typeof import("../components/section/pets/Noticefindowner.vue")['default']
export const SectionPetsNoticelostpets: typeof import("../components/section/pets/Noticelostpets.vue")['default']
export const SectionPetsPetButtons: typeof import("../components/section/pets/PetButtons.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LCircle: typeof import("@vue-leaflet/vue-leaflet")['LCircle']
export const LCircleMarker: typeof import("@vue-leaflet/vue-leaflet")['LCircleMarker']
export const LControl: typeof import("@vue-leaflet/vue-leaflet")['LControl']
export const LControlAttribution: typeof import("@vue-leaflet/vue-leaflet")['LControlAttribution']
export const LControlLayers: typeof import("@vue-leaflet/vue-leaflet")['LControlLayers']
export const LControlScale: typeof import("@vue-leaflet/vue-leaflet")['LControlScale']
export const LControlZoom: typeof import("@vue-leaflet/vue-leaflet")['LControlZoom']
export const LFeatureGroup: typeof import("@vue-leaflet/vue-leaflet")['LFeatureGroup']
export const LGeoJson: typeof import("@vue-leaflet/vue-leaflet")['LGeoJson']
export const LIcon: typeof import("@vue-leaflet/vue-leaflet")['LIcon']
export const LImageOverlay: typeof import("@vue-leaflet/vue-leaflet")['LImageOverlay']
export const LLayerGroup: typeof import("@vue-leaflet/vue-leaflet")['LLayerGroup']
export const LMap: typeof import("@vue-leaflet/vue-leaflet")['LMap']
export const LMarker: typeof import("@vue-leaflet/vue-leaflet")['LMarker']
export const LPolygon: typeof import("@vue-leaflet/vue-leaflet")['LPolygon']
export const LPolyline: typeof import("@vue-leaflet/vue-leaflet")['LPolyline']
export const LPopup: typeof import("@vue-leaflet/vue-leaflet")['LPopup']
export const LRectangle: typeof import("@vue-leaflet/vue-leaflet")['LRectangle']
export const LTileLayer: typeof import("@vue-leaflet/vue-leaflet")['LTileLayer']
export const LTooltip: typeof import("@vue-leaflet/vue-leaflet")['LTooltip']
export const LWmsTileLayer: typeof import("@vue-leaflet/vue-leaflet")['LWmsTileLayer']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyLcAdmin: typeof import("../components/lc/admin/index.vue")['default']
export const LazyLcFooter: typeof import("../components/lc/footer/index.vue")['default']
export const LazyLcHeader: typeof import("../components/lc/header/index.vue")['default']
export const LazyLcLogoFooterPets: typeof import("../components/lc/logo/FooterPets.vue")['default']
export const LazyLcLogoLostPets: typeof import("../components/lc/logo/LostPets.vue")['default']
export const LazyLcLogoNoticePets: typeof import("../components/lc/logo/NoticePets.vue")['default']
export const LazyLcLogoPetsCatDog: typeof import("../components/lc/logo/PetsCatDog.vue")['default']
export const LazyLcLogoPetsLogo: typeof import("../components/lc/logo/PetsLogo.vue")['default']
export const LazyLcLogoTargetPets: typeof import("../components/lc/logo/TargetPets.vue")['default']
export const LazyLcUser: typeof import("../components/lc/user/index.vue")['default']
export const LazySectionAbout: typeof import("../components/section/About/About.vue")['default']
export const LazySectionAdminAdoptpettable: typeof import("../components/section/Admin/Adoptpettable.vue")['default']
export const LazySectionAdminFindownertable: typeof import("../components/section/Admin/Findownertable.vue")['default']
export const LazySectionAdminGallerytable: typeof import("../components/section/Admin/Gallerytable.vue")['default']
export const LazySectionAdminLostpetstable: typeof import("../components/section/Admin/Lostpetstable.vue")['default']
export const LazySectionAdminProducttable: typeof import("../components/section/Admin/Producttable.vue")['default']
export const LazySectionAdminUsertable: typeof import("../components/section/Admin/Usertable.vue")['default']
export const LazySectionAdoptpetAdoptpetpage: typeof import("../components/section/Adoptpet/Adoptpetpage.vue")['default']
export const LazySectionAllAdmin: typeof import("../components/section/AllAdmin.vue")['default']
export const LazySectionAllAdoptpet: typeof import("../components/section/AllAdoptpet.vue")['default']
export const LazySectionAllArticle: typeof import("../components/section/AllArticle.vue")['default']
export const LazySectionAllBanner: typeof import("../components/section/AllBanner.vue")['default']
export const LazySectionAllFindowner: typeof import("../components/section/AllFindowner.vue")['default']
export const LazySectionAllHome: typeof import("../components/section/AllHome.vue")['default']
export const LazySectionAllProducts: typeof import("../components/section/AllProducts.vue")['default']
export const LazySectionArticleArticlemain: typeof import("../components/section/Article/Articlemain.vue")['default']
export const LazySectionArticleArticlepage: typeof import("../components/section/Article/Articlepage.vue")['default']
export const LazySectionEditusee: typeof import("../components/section/Edituser.vue")['default']
export const LazySectionFindownerFindownerpage: typeof import("../components/section/Findowner/Findownerpage.vue")['default']
export const LazySectionHomeAbouthome: typeof import("../components/section/Home/Abouthome.vue")['default']
export const LazySectionHomeAboutnoticehome: typeof import("../components/section/Home/Aboutnoticehome.vue")['default']
export const LazySectionLogin: typeof import("../components/section/Login.vue")['default']
export const LazySectionMappin: typeof import("../components/section/Mappin.vue")['default']
export const LazySectionProductProductsmain: typeof import("../components/section/Product/Productsmain.vue")['default']
export const LazySectionProductProductspage: typeof import("../components/section/Product/Productspage.vue")['default']
export const LazySectionProductSortButtons: typeof import("../components/section/Product/SortButtons.vue")['default']
export const LazySectionRegister: typeof import("../components/section/Register.vue")['default']
export const LazySectionTest: typeof import("../components/section/Test.vue")['default']
export const LazySectionUserTabpets: typeof import("../components/section/User/Tabpets.vue")['default']
export const LazySectionBannerBannerlostpets: typeof import("../components/section/banner/Bannerlostpets.vue")['default']
export const LazySectionBannerGallery: typeof import("../components/section/banner/Gallery.vue")['default']
export const LazySectionPetsAdoptpet: typeof import("../components/section/pets/Adoptpet.vue")['default']
export const LazySectionPetsAllpets: typeof import("../components/section/pets/Allpets.vue")['default']
export const LazySectionPetsFindowner: typeof import("../components/section/pets/Findowner.vue")['default']
export const LazySectionPetsImageUpload: typeof import("../components/section/pets/ImageUpload.vue")['default']
export const LazySectionPetsLostpets: typeof import("../components/section/pets/Lostpets.vue")['default']
export const LazySectionPetsNoticeadoptpet: typeof import("../components/section/pets/Noticeadoptpet.vue")['default']
export const LazySectionPetsNoticefindowner: typeof import("../components/section/pets/Noticefindowner.vue")['default']
export const LazySectionPetsNoticelostpets: typeof import("../components/section/pets/Noticelostpets.vue")['default']
export const LazySectionPetsPetButtons: typeof import("../components/section/pets/PetButtons.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyLCircle: typeof import("@vue-leaflet/vue-leaflet")['LCircle']
export const LazyLCircleMarker: typeof import("@vue-leaflet/vue-leaflet")['LCircleMarker']
export const LazyLControl: typeof import("@vue-leaflet/vue-leaflet")['LControl']
export const LazyLControlAttribution: typeof import("@vue-leaflet/vue-leaflet")['LControlAttribution']
export const LazyLControlLayers: typeof import("@vue-leaflet/vue-leaflet")['LControlLayers']
export const LazyLControlScale: typeof import("@vue-leaflet/vue-leaflet")['LControlScale']
export const LazyLControlZoom: typeof import("@vue-leaflet/vue-leaflet")['LControlZoom']
export const LazyLFeatureGroup: typeof import("@vue-leaflet/vue-leaflet")['LFeatureGroup']
export const LazyLGeoJson: typeof import("@vue-leaflet/vue-leaflet")['LGeoJson']
export const LazyLIcon: typeof import("@vue-leaflet/vue-leaflet")['LIcon']
export const LazyLImageOverlay: typeof import("@vue-leaflet/vue-leaflet")['LImageOverlay']
export const LazyLLayerGroup: typeof import("@vue-leaflet/vue-leaflet")['LLayerGroup']
export const LazyLMap: typeof import("@vue-leaflet/vue-leaflet")['LMap']
export const LazyLMarker: typeof import("@vue-leaflet/vue-leaflet")['LMarker']
export const LazyLPolygon: typeof import("@vue-leaflet/vue-leaflet")['LPolygon']
export const LazyLPolyline: typeof import("@vue-leaflet/vue-leaflet")['LPolyline']
export const LazyLPopup: typeof import("@vue-leaflet/vue-leaflet")['LPopup']
export const LazyLRectangle: typeof import("@vue-leaflet/vue-leaflet")['LRectangle']
export const LazyLTileLayer: typeof import("@vue-leaflet/vue-leaflet")['LTileLayer']
export const LazyLTooltip: typeof import("@vue-leaflet/vue-leaflet")['LTooltip']
export const LazyLWmsTileLayer: typeof import("@vue-leaflet/vue-leaflet")['LWmsTileLayer']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
